name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
          echo "Hello World"
          echo "Hello World second time"
      - name: Print goodbye
        run: echo "Done - Bye"
